version: '3.6'
services:
  service-library:
    image: 'service-library:latest'
    build:
      context: .
    container_name: service-library
    expose:
      - 8080
    ports:
      - 8086:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library_postgres:5432/library
      - SPRING_DATASOURCE_USERNAME=kuper
      - SPRING_DATASOURCE_PASSWORD=abcd1234

  postgres:
    build: ./docker/postgres
    container_name: library_postgres
    expose:
      - 5432
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=kuper
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_DB=library